version: '3.7'

services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: invoice
      POSTGRES_USER: invoice
      POSTGRES_DB: invoice
      TZ: "UTC"
    volumes:
      - invoicedbdata:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: ${IP_PREFIX}.3
    env_file: .env

  db_test:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: invoice
      POSTGRES_USER: invoice
      POSTGRES_DB: invoice_test
      TZ: "UTC"
    volumes:
      - invoicedbtestdata:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: ${IP_PREFIX}.4
    env_file: .env

  web:
    image: webdevops/php-nginx-dev:8.0
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_DATE_TIMEZONE: "UTC"
      TZ: "UTC"
    networks:
      default:
        ipv4_address: ${IP_PREFIX}.2

volumes:
  invoicedbdata:
  invoicedbtestdata:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${IP_PREFIX}.0/24